spring :
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tagtag1010
    url: jdbc:mysql://localhost:3307/test01

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: clonecoding.velog_clone.dto
